redone s6 init
- changed components to run as root - expected by hassio
- fixed custom scripts/callbacks dir

diff --git a/ntopng/rootfs/etc/s6-overlay/s6-rc.d/geoip/run b/ntopng/rootfs/etc/s6-overlay/s6-rc.d/geoip/run
--- a/ntopng/rootfs/etc/s6-overlay/s6-rc.d/geoip/run
+++ b/ntopng/rootfs/etc/s6-overlay/s6-rc.d/geoip/run
@@ -4,26 +4,36 @@
 # Runs the netflow2ng daemon
 # ==============================================================================
 
-bashio::log.info "Starting Maxmind Database update runner..."
+bashio::log.info "Starting GeoIP database update runner..."
 
 while true
 do
-    bashio::log.info "Geoip is configured"
     if bashio::fs.file_exists /etc/GeoIP.conf; then
-        bashio::log.info "Checking state of the geoip database."
-        cnt=0
-        #cnt=$(find /data/geoip/*.mmdb -mtime -1 -print 2>/dev/null | wc -l)
-
+        bashio::log.info "Checking state of the GeoIP database."
+        if ! bashio::fs.directory_exists /data/geoip; then
+            bashio::log.info "GeoIP database directory does not exist."
+            sleep 5
+            continue
+        fi
         # Update GeoIP database if doesn't exist or is older then 1 day
+        cnt=$(find /data/geoip/*.mmdb -mtime -1 -print 2>/dev/null | wc -l)
         if [[ "$cnt" -eq 3 ]]; then
-            bashio::log.info "Maxmind Database is up-to-date."
+            bashio::log.info "GeoIP database is up-to-date."
         else
             rm -f /var/run/geoip/finished
-            bashio::log.info "Updating Maxmind Database..."
-            s6-setuidgid geoip /usr/bin/geoipupdate
-            bashio::log.info "Maxmind Database updated."
-            s6-setuidgid geoip touch /var/run/geoip/finished
+            bashio::log.info "Updating GeoIP database..."
+            exec /usr/bin/geoipupdate
+            if $? -ne 0; then
+                bashio::log.error "GeoIP database update failed."
+                sleep 60
+                continue
+            else
+                bashio::log.info "GeoIP database updated."
+                touch /var/run/geoip/finished
+            fi
         fi
+    else
+        bashio::log.info "GeoIP configuration not found, skipping database update."
     fi
     sleep 21600
 done
